// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

/**
 * 
 */
namespace SRGameplayTags
{
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_ID_Move);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_ID_PickupItem);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_ID_ClosePickupItemPopup);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_ID_OepnInvenstigation);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_ID_ClickClueButton);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_ID_CombineClue);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_ID_ClickClueMapButton);



	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_Objectives_Move);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_Objectives_PickupItem);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_Objectives_ClosePickupItemPopup);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_Objectives_OepnInvenstigation);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_Objectives_ClickClueButton);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_Objectives_CombineClue);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_Objectives_ClickClueMapButton);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameFlow_Objectives_UseFirstFill);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameFlow_Objectives_UsePillActiveDataArchiveRoomKey);


	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameFlow_Chapter2Complete);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameFlow_Chapter3Complete);
	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameFlow_Chapter4Complete);

	SUBJECT_REM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameFlow_Objectives_CobmineAudio);


}
